### ISSUE TITLE
HOWTO Install RanSEPS in 2024 in AlmaLinux8.9

### ISSUE THREAD

**Issue by ocstx** [SMV818VMS/RanSEPs#5]
Hi
I will have to run RanSEQS in the following months so I tried to install it.
Since it is python and 2.7, I was expecting problems and Indeed I found them.

But apparently it is working.

I'm in AlmaLinux 8.9 (For those who don't know: a Binary compatible RHEL clone born after Cento8 had an early decommission )

Please NOTE:
Here is the contens of my new requirements.txt file:
```
biopython==1.70
numpy==1.13.1
pandas==0.23.4
matplotlib==2.2.3
scipy==1.0.0
scikit-learn==0.20.4
setuptools==36.0.1
```

Here is what I did

make supre python2.7 and virtualenv-2.7 are installed

At some point I got this Error:
python2.7 ImportError: No module named Tkinter
so I had to install it from the system:

`dnf install python2-tkinter.x86_64`

```
mkdir RANSEPS
cd RANSEPS
git clone https://github.com/samuelmiver/RanSEPs.git

```
cd to the RanSEPS and modify setup.py to change requirement sklearn for scikit-learn
here I'm pasting lines 17 and 18 for my modifed setup.py:
```
#     17     'install_requires': ['biopython','numpy','pandas','matplotlib',
#     18                          'scipy','scikit-learn', 'setuptools'],

```

Create a python2.7 venv
`virtualenv-2.7 -p /usr/bin/python2.7 RANSEPS_VE_REDO`
Load it
`source RANSEPS_VE_REDO/bin/activate`

install the new requirements I previously commented
`pip2 install -r requirements-VERSIONS.txt
`
download the old propy (propy-1.0) (or is it protpy?)
```
wget "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/protpy/propy-1.0.tar.gz"
tar zxf propy-1.0.tar.gz
cd propy-1.0/
python2.7 setup.py install
cd ..

```
```
cd RanSEPs
python2.7 setup.py install

```
to test it execute
`ranseps -h`

# Running it
I wanted to test it with this:
`https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nuccore&id=NC_000908&rettype=gbwithparts&retmode=text
`
according to the README the following should work:
`ranseps -g NC_000908.gbff`

but it did not. The Last ERROR line was:
```
  File "/home/$USER/BIOSOFT/MLLUCH/RANSEPS/RANSEPS_VE/lib/python2.7/site-packages/ranseps-0.0.1-py2.7.egg/ranseps/run_ranseps.py", line 25, in format_genome_cds
    Ns = genome.count('N')
AttributeError: 'NoneType' object has no attribute 'count'

```
So I extracted the DNA from the chromosome in the file:
`NC_000908.gbff.crom.fst`

and the DNA sequences from CDSs i in the file:
`NC_010943.1-2022.gbff.dna.fst`

and executed:

```
# You need blast in your path for ranseps to work
BLAST_BINDIR=$HOME/BIOSOFT/BLAST/blast-latest/bin
export PATH=$BLAST_BINDIR:$PATH
# prevent matplotlib to try to open a window if you are working remote (See below)
export MPLBACKEND=AGG
time ranseps -t 4 -g NOPSEUDO_ONLYCDS/NC_000908.gbff.crom.fst -c NOPSEUDO_ONLYCDS/NC_010943.1-2022.gbff.dna.fst -o MGEG37_RANSEPS
```

and it worked !
I used a really old CPU so it took a while:
real    46m2.949s
user    100m23.539s
sys     0m12.656s

But it's ok, it works! :)

# Additional note:
regarding:
```
export MPLBACKEND=AGG
```
I'm running it in a remote server and using tmux so I can disconnect from it.
On my first runs I got some early error from tkinter complaining about not finding a display. So I recconented using
``` ssh -Y```
(ssh -X should work as well)
But still after some running time I got this error:
```
XIO: fatal IO error 25 (Inappropriate ioctl for device) on X server "localhost:10.0"
```
It can be solved changing the matplotlib backend. One way to do it is modifying the environment variable MPLBACKEND
more information here:
https://matplotlib.org/stable/users/explain/figure/backends.html
and here
https://stackoverflow.com/questions/45993879/matplot-lib-fatal-io-error-25-inappropriate-ioctl-for-device-on-x-server-loc

**Comment by maurijlozano** [comment]
Thank you for your comments it could have saved me some time...
I had the same errors in Linux mint (and ubuntu) and figure out the same solutions...
However i have a diferente error while running...

```bash
$ ranseps -g sequence.gb

....

  File ".local/lib/python2.7/site-packages/Bio/motifs/__init__.py", line 24, in create
    return Motif(instances=instances, alphabet=alphabet)
  File ".local/lib/python2.7/site-packages/Bio/motifs/__init__.py", line 273, in __init__
    counts = self.instances.count()
  File .local/lib/python2.7/site-packages/Bio/motifs/__init__.py", line 220, in count
    for letter in self.alphabet:
TypeError: 'NoneType' object is not iterable
```
Using -c coding sequences didn't solve the issue...

**Comment by samuelmiver** [comment]
Dear @ocstx, @maurijlozano, 

Apologies for my silence and for the problems experienced. I have very limited time to work on this right now but I am close to provide a refactored version with updated python and packages versions. However, I am currently facing different problems on some parts I need to test properly to ensure it does the same. 

For now, I have updated the `requirements.txt` in this repo to match those from the environment that allows me to run ranseps with no errors. The `self.alphabet` error should not happen with biopython 1.70. 

Also, I recommend you specify the codon table by calling `ranseps -g {genome} -t 11 -o {output}` or `-t 0 -c {CDS_file}`. This will make the computation less expensive at the cost of loosing smORFs with non-traditional start codons (which we really think are not expressed).

**Comment by ocstx** [comment]
It works for me now!
I updated the instructions at the beginning of this issue so if anybody needs to install it, he or she can follow them

**Comment by maurijlozano** [comment]
Thank you for the instructions!
I'll try it soon.
